# Generated by Django 5.1.1 on 2024-09-19 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('achievement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('highest_score', models.BooleanField(default=False)),
                ('game_type', models.CharField(choices=[('dino', 'Dino'), ('counting-stars', 'Counting Stars'), ('snake', 'Snake'), ('shooting', 'Shooting')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'achievement_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'game_type'), name='unique_score_per_game')],
            },
        ),
    ]
